// 《江湖丛谈》江湖黑话词典
// 来源：连阔如著《江湖丛谈》

export interface JargonEntry {
  term: string;        // 江湖黑话
  meaning: string;    // 大白话意思
  category: string;   // 分类
  example?: string;    // 用法示例
}

export const JARGON_DICTIONARY: JargonEntry[] = [
  // ===== 人物称谓类 =====
  { term: "春点", meaning: "江湖人用的暗语/行话，类似于暗号", category: "基础术语" },
  { term: "调侃", meaning: "说暗语、行话", category: "基础术语" },
  { term: "侃儿", meaning: "江湖暗语本身", category: "基础术语" },
  { term: "老合", meaning: "江湖同行、江湖艺人", category: "人物称谓" },
  { term: "生意人", meaning: "在江湖上做买卖的人", category: "人物称谓" },
  { term: "空子", meaning: "不懂江湖事的外行人", category: "人物称谓" },
  { term: "半开眼", meaning: "对江湖事一知半解的人", category: "人物称谓" },
  { term: "跳板", meaning: "初入江湖的新手", category: "人物称谓" },
  { term: "杵儿", meaning: "钱、收入", category: "基础术语" },
  { term: "治杵儿", meaning: "挣到钱", category: "基础术语" },
  { term: "迎门杵", meaning: "顾客给的价钱", category: "基础术语" },
  
  // ===== 人物称谓详细 =====
  { term: "孙食", meaning: "男人", category: "人物" },
  { term: "果食", meaning: "媳妇、已婚妇女", category: "人物" },
  { term: "苍果", meaning: "老太太", category: "人物" },
  { term: "姜斗", meaning: "大姑娘", category: "人物" },
  { term: "斗花子", meaning: "小姑娘", category: "人物" },
  { term: "怎科子", meaning: "小男孩", category: "人物" },
  { term: "老戗", meaning: "父亲", category: "人物" },
  { term: "磨头", meaning: "母亲", category: "人物" },
  { term: "上排琴", meaning: "哥哥", category: "人物" },
  { term: "下排琴", meaning: "弟弟", category: "人物" },
  { term: "戗儿的戗", meaning: "祖父", category: "人物" },
  { term: "戗的磨头", meaning: "祖母", category: "人物" },
  { term: "库果", meaning: "妓女", category: "人物" },
  { term: "子孙窖儿", meaning: "良家妇女", category: "人物" },
  { term: "展点", meaning: "男仆、男佣人", category: "人物" },
  { term: "展果", meaning: "女仆、女佣人", category: "人物" },
  { term: "海冷", meaning: "当兵的", category: "人物" },
  { term: "鹰爪", meaning: "侦探、警察", category: "人物" },
  { term: "老荣", meaning: "小偷、扒手", category: "人物" },
  { term: "治把", meaning: "和尚", category: "人物" },
  { term: "化把", meaning: "老道、道士", category: "人物" },
  { term: "念把", meaning: "尼姑", category: "人物" },
  { term: "冷子点", meaning: "当官的", category: "人物" },
  { term: "海翅子", meaning: "大官", category: "人物" },
  { term: "色唐点", meaning: "外国人", category: "人物" },
  { term: "科郎码", meaning: "乡下人、农村人", category: "人物" },
  { term: "念攒子", meaning: "傻子", category: "人物" },
  { term: "丢子点", meaning: "疯子", category: "人物" },
  { term: "朗不正", meaning: "坏人、恶人", category: "人物" },
  { term: "忠样点", meaning: "好人", category: "人物" },
  { term: "臭子点", meaning: "好色的人、色鬼", category: "人物" },
  { term: "火点", meaning: "有钱的财主", category: "人物" },
  { term: "水码子", meaning: "穷人", category: "人物" },
  { term: "銮把点", meaning: "好赌钱的人、赌徒", category: "人物" },
  { term: "念招点", meaning: "瞎子", category: "人物" },
  
  // ===== 方位时间类 =====
  { term: "顶", meaning: "天", category: "方位" },
  { term: "躺", meaning: "地", category: "方位" },
  { term: "倒", meaning: "东边/东", category: "方位" },
  { term: "切", meaning: "西边/西", category: "方位" },
  { term: "阳", meaning: "南边/南", category: "方位" },
  { term: "密", meaning: "北边/北", category: "方位" },
  { term: "梁", meaning: "大路、大道", category: "方位" },
  
  // ===== 天气现象类 =====
  { term: "摆丢子", meaning: "刮风", category: "天气" },
  { term: "摆金", meaning: "下雨", category: "天气" },
  { term: "摆银", meaning: "下雪", category: "天气" },
  { term: "牐棚儿", meaning: "阴天", category: "天气" },
  { term: "鞭轰儿", meaning: "打雷", category: "天气" },
  
  // ===== 日常动作类 =====
  { term: "安根", meaning: "吃饭", category: "动作" },
  { term: "念啃", meaning: "挨饿、饿着", category: "动作" },
  { term: "抛山", meaning: "拉屎", category: "动作" },
  { term: "窍", meaning: "走吧", category: "动作" },
  { term: "鞭托", meaning: "打架", category: "动作" },
  { term: "攒稀", meaning: "害怕", category: "动作" },
  { term: "扯活", meaning: "跑了、逃走", category: "动作" },
  { term: "土了点啦", meaning: "人死了", category: "动作" },
  { term: "怀儿怎啦", meaning: "妇人怀孕", category: "动作" },
  { term: "咧了瓢儿", meaning: "笑了", category: "动作" },
  { term: "抖搂包袱", meaning: "用各种方法逗人笑", category: "动作" },
  { term: "攥弄活儿", meaning: "自己会编段子", category: "动作" },
  { term: "啃海草儿", meaning: "抽大烟、吸毒", category: "动作" },
  { term: "朝翅子", meaning: "打官司", category: "动作" },
  
  // ===== 物品器具类 =====
  { term: "塌笼", meaning: "房子、房间", category: "物品" },
  { term: "窑儿", meaning: "店、店铺", category: "物品" },
  { term: "牙淋窑儿", meaning: "茶馆", category: "物品" },
  { term: "库果窑儿", meaning: "妓院", category: "物品" },
  { term: "拱页瓤子", meaning: "当铺", category: "物品" },
  { term: "挑拱页子", meaning: "卖当票的人", category: "物品" },
  { term: "招汉座子", meaning: "开铺子卖药的", category: "物品" },
  { term: "转枝子", meaning: "表、手表", category: "物品" },
  { term: "顶笼", meaning: "帽子", category: "物品" },
  { term: "通天洒", meaning: "大褂、长衫", category: "物品" },
  { term: "登空子", meaning: "裤子", category: "物品" },
  { term: "踢土儿", meaning: "鞋子", category: "物品" },
  { term: "熏筒儿", meaning: "袜子", category: "物品" },
  { term: "挂洒", meaning: "衣服", category: "物品" },
  { term: "挂酒火", meaning: "穿得很阔气、很有钱的样子", category: "物品" },
  { term: "挂洒水", meaning: "穿得很破烂", category: "物品" },
  { term: "轮子", meaning: "车", category: "物品" },
  { term: "戳子", meaning: "笔", category: "物品" },
  { term: "朵儿", meaning: "字", category: "物品" },
  { term: "青子", meaning: "刀", category: "物品" },
  { term: "喷子", meaning: "枪", category: "物品" },
  { term: "喷子升点儿", meaning: "放枪", category: "物品" },
  { term: "汉轰", meaning: "药", category: "物品" },
  { term: "错齿子", meaning: "肉", category: "物品" },
  { term: "龙宫", meaning: "水", category: "物品" },
  
  // ===== 动物类 =====
  { term: "风子", meaning: "马", category: "动物" },
  { term: "岔子", meaning: "牛", category: "动物" },
  { term: "金扶柳", meaning: "驴", category: "动物" },
  { term: "月宫嘴子", meaning: "兔子", category: "动物" },
  { term: "海嘴子", meaning: "老虎", category: "动物" },
  { term: "海条子", meaning: "龙", category: "动物" },
  { term: "土条子", meaning: "蛇", category: "动物" },
  { term: "悬梁子", meaning: "桥", category: "物品" },
  
  // ===== 饮食类 =====
  { term: "肘山", meaning: "买酒", category: "饮食" },
  { term: "抿山", meaning: "喝酒", category: "饮食" },
  { term: "串山", meaning: "喝醉了", category: "饮食" },
  { term: "火山", meaning: "烧酒、白酒", category: "饮食" },
  { term: "幌幌山", meaning: "黄酒", category: "饮食" },
  
  // ===== 形容类 =====
  { term: "梅花盘", meaning: "麻子脸", category: "形容" },
  { term: "盘儿嘬", meaning: "人长得很漂亮", category: "形容" },
  { term: "盘儿念嘬", meaning: "人长得很丑", category: "形容" },
  { term: "嘴子", meaning: "野妓", category: "人物" },
  { term: "空心果", meaning: "寡妇", category: "人物" },
  { term: "柴", meaning: "牙齿", category: "身体" },
  { term: "团黄粱子", meaning: "梦", category: "物品" },
  
  // ===== 江湖行业八大门 =====
  { term: "金门/金点", meaning: "算卦的行业", category: "江湖八门" },
  { term: "皮门/皮点", meaning: "卖药的行业", category: "江湖八门" },
  { term: "彩门/彩", meaning: "变戏法的行业", category: "江湖八门" },
  { term: "挂门/挂", meaning: "打把势卖艺的行业", category: "江湖八门" },
  { term: "平门/平", meaning: "说评书的行业", category: "江湖八门" },
  { term: "团门/团春", meaning: "说相声的行业", category: "江湖八门" },
  { term: "调门/调", meaning: "唱大鼓等曲艺的行业", category: "江湖八门" },
  { term: "柳门/柳", meaning: "唱戏的行业", category: "江湖八门" },
  { term: "风门", meaning: "以骗术为业", category: "江湖八门" },
  { term: "马门", meaning: "看相算命", category: "江湖八门" },
  { term: "雁门", meaning: "小偷", category: "江湖八门" },
  { term: "雀门", meaning: "赌博作弊", category: "江湖八门" },
  { term: "穷家门", meaning: "乞丐", category: "江湖八门" },
  
  // ===== 江湖动作/状态 =====
  { term: "夹磨", meaning: "教徒弟的本领", category: "动作" },
  { term: "鞭", meaning: "打（徒弟）", category: "动作" },
  { term: "团春", meaning: "说相声", category: "动作" },
  { term: "臭春", meaning: "说相声（贬义）", category: "动作" },
  { term: "挂托", meaning: "变戏法在道具上弄鬼", category: "动作" },
  { term: "荣门", meaning: "偷东西", category: "动作" },
  { term: "跨点", meaning: "拉到住处", category: "动作" },
  { term: "黏子", meaning: "围观的观众", category: "状态" },
  { term: "大黏子", meaning: "观众很多", category: "状态" },
  { term: "小黏子/圆小黏子", meaning: "观众少", category: "状态" },
  { term: "边黏子不动", meaning: "围观的人不走", category: "状态" },
  { term: "火穴大转", meaning: "很能赚钱", category: "状态" },
  { term: "杵门", meaning: "要钱、收钱", category: "动作" },
  { term: "穴儿", meaning: "搭档、伙伴", category: "人物" },
  { term: "摇钱树", meaning: "能挣钱的人/项目", category: "状态" },
  { term: "闷了", meaning: "冷场、没人笑", category: "状态" },
  { term: "抖搂闷了", meaning: "逗笑失败", category: "状态" },
  { term: "包袱", meaning: "笑料、段子", category: "状态" },
  { term: "素包袱", meaning: "不含荤段子的笑料", category: "状态" },
  { term: "响儿", meaning: "笑声", category: "状态" },
  { term: "人式旺", meaning: "人多热闹", category: "状态" },
  { term: "人式太减", meaning: "观众太少", category: "状态" },
  { term: "攒儿亮", meaning: "明白江湖事", category: "状态" },
  { term: "月顶码子", meaning: "两个人", category: "数量" },
  { term: "摇个其", meaning: "一块钱", category: "数量" },
];

export const CATEGORIES = [
  { name: "全部", icon: "📚" },
  { name: "基础术语", icon: "🔤" },
  { name: "人物", icon: "👤" },
  { name: "方位", icon: "🧭" },
  { name: "天气", icon: "🌤️" },
  { name: "动作", icon: "🤜" },
  { name: "物品", icon: "📦" },
  { name: "动物", icon: "🐴" },
  { name: "饮食", icon: "🍺" },
  { name: "形容", icon: "😊" },
  { name: "江湖八门", icon: "🏛️" },
  { name: "状态", icon: "📊" },
  { name: "数量", icon: "🔢" },
];

export const SEARCH_EXAMPLES = [
  "孙食",
  "春点",
  "杵儿",
  "空子",
  "果食",
  "海冷",
  "火点",
  "摆金",
  "挂托",
  "抖搂包袱",
];
